name: Build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
